"""Adding more fields to user column

Revision ID: 11cb9317ac42
Revises: 38bfc5874289
Create Date: 2022-04-11 23:17:38.662308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11cb9317ac42'
down_revision = '38bfc5874289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=False))
    op.drop_constraint('user_senha_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['password'])
    op.drop_column('user', 'senha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('senha', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_senha_key', 'user', ['senha'])
    op.drop_column('user', 'admin')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
