"""Alter User Table Add Password Column

Revision ID: 38bfc5874289
Revises: 
Create Date: 2022-04-05 02:32:19.266322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bfc5874289'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('senha', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['senha'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'senha')
    # ### end Alembic commands ###
