"""adding role enum on users table

Revision ID: f898b74b38e5
Revises: 11cb9317ac42
Create Date: 2022-04-11 23:59:29.283880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f898b74b38e5'
down_revision = '11cb9317ac42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    roles = postgresql.ENUM('MANAGER', 'OPERATION', 'INTERN', name='roles')
    roles.create(op.get_bind())
    op.add_column('user', sa.Column('role', sa.Enum('MANAGER','OPERATION', 'INTERN', name='roles'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    roles = postgresql.ENUM('MANAGER', 'OPERATION', 'INTERN', name='roles')
    roles.drop(op.get_bind())
    # ### end Alembic commands ###
